os: linux
dist: xenial
language: julia
julia:
  - nightly
  - 1.0.6
  - 1.5.2

install:
- julia --project -e 'import Pkg; Pkg.add("Plots");'
- julia --project -e 'import Pkg; Pkg.add("FlameGraphs");'

script: julia -L src/Sirion.jl tests/runtests.jl